name: tnc
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - abseil-cpp=20211102.0
  - altair=4.2.2
  - appdirs=1.4.4
  - appnope=0.1.3
  - arrow-cpp=11.0.0
  - asttokens=2.2.1
  - attrs=22.2.0
  - aws-c-common=0.4.57
  - aws-c-event-stream=0.1.6
  - aws-checksums=0.1.9
  - aws-sdk-cpp=1.8.185
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - blas=1.0
  - blinker=1.6.2
  - boost-cpp=1.78.0
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2022.12.7
  - cachetools=5.3.0
  - catalogue=2.0.8
  - certifi=2022.12.7
  - cffi=1.15.1
  - charset-normalizer=3.1.0
  - click=8.1.3
  - colorama=0.4.6
  - comm=0.1.3
  - confection=0.0.4
  - cryptography=3.4.8
  - cycler=0.11.0
  - cymem=2.0.7
  - cython-blis=0.7.9
  - dataclasses=0.8
  - debugpy=1.6.7
  - decorator=5.1.1
  - entrypoints=0.4
  - executing=1.2.0
  - fonttools=4.39.3
  - freetype=2.10.4
  - gflags=2.2.2
  - giflib=5.2.1
  - gitdb=4.0.10
  - gitpython=3.1.31
  - glog=0.5.0
  - grpc-cpp=1.46.1
  - icu=70.1
  - idna=3.4
  - importlib-metadata=6.5.0
  - importlib_metadata=6.5.0
  - importlib_resources=5.12.0
  - ipykernel=6.22.0
  - ipython=8.12.0
  - ipywidgets=8.0.6
  - jedi=0.18.2
  - jinja2=3.1.2
  - joblib=1.1.0
  - jpeg=9e
  - jsonschema=4.17.3
  - jupyter_client=8.2.0
  - jupyter_core=5.3.0
  - jupyterlab_widgets=3.0.7
  - kiwisolver=1.4.4
  - krb5=1.19.3
  - langcodes=3.3.0
  - lcms2=2.15
  - lerc=3.0
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libcurl=7.87.0
  - libcxx=14.0.6
  - libdeflate=1.17
  - libedit=3.1.20191231
  - libev=4.33
  - libevent=2.1.10
  - libffi=3.4.2
  - libgfortran=5.0.0
  - libgfortran5=12.2.0
  - liblapack=3.9.0
  - libnghttp2=1.46.0
  - libopenblas=0.3.21
  - libpng=1.6.39
  - libprotobuf=3.20.3
  - libsodium=1.0.18
  - libssh2=1.10.0
  - libthrift=0.15.0
  - libtiff=4.5.0
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - llvm-openmp=16.0.1
  - lz4-c=1.9.4
  - markdown-it-py=2.2.0
  - markupsafe=2.1.2
  - matplotlib-base=3.5.3
  - matplotlib-inline=0.1.6
  - mdurl=0.1.0
  - munkres=1.1.4
  - murmurhash=1.0.9
  - ncurses=6.4
  - nest-asyncio=1.5.6
  - numpy=1.24.2
  - openssl=1.1.1t
  - orc=1.7.4
  - packaging=23.1
  - pandas=1.5.3
  - parso=0.8.3
  - pathy=0.10.1
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=9.4.0
  - pip=23.0.1
  - pkgutil-resolve-name=1.3.10
  - platformdirs=3.2.0
  - pooch=1.4.0
  - preshed=3.0.8
  - prompt-toolkit=3.0.38
  - prompt_toolkit=3.0.38
  - protobuf=3.20.3
  - psutil=5.9.5
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pyarrow=11.0.0
  - pycparser=2.21
  - pydantic=1.10.7
  - pydeck=0.8.0
  - pygments=2.15.1
  - pympler=1.0.1
  - pyopenssl=20.0.1
  - pyparsing=3.0.9
  - pyrsistent=0.19.3
  - pysocks=1.7.1
  - python=3.9.16
  - python-dateutil=2.8.2
  - python-tzdata=2023.3
  - python_abi=3.9
  - pytz=2023.3
  - pytz-deprecation-shim=0.1.0.post0
  - pyyaml=6.0
  - pyzmq=25.0.2
  - re2=2022.04.01
  - readline=8.2
  - requests=2.28.2
  - rich=13.3.4
  - scikit-learn=1.0.2
  - scipy=1.10.1
  - setuptools=66.0.0
  - shellingham=1.5.1
  - six=1.16.0
  - smart_open=5.2.1
  - smmap=3.0.5
  - snappy=1.1.10
  - spacy=3.5.2
  - spacy-legacy=3.0.12
  - spacy-loggers=1.0.4
  - sqlite=3.41.2
  - srsly=2.4.6
  - stack_data=0.6.2
  - streamlit=1.21.0
  - thinc=8.1.9
  - threadpoolctl=2.2.0
  - tk=8.6.12
  - toml=0.10.2
  - toolz=0.12.0
  - tornado=6.3
  - tqdm=4.65.0
  - traitlets=5.9.0
  - typer=0.4.2
  - typing-extensions=4.5.0
  - typing_extensions=4.5.0
  - tzdata=2023c
  - tzlocal=4.3
  - unicodedata2=15.0.0
  - urllib3=1.26.15
  - utf8proc=2.6.1
  - validators=0.20.0
  - wasabi=1.1.1
  - watchdog=3.0.0
  - wcwidth=0.2.6
  - wheel=0.38.4
  - widgetsnbextension=4.0.7
  - wordcloud=1.8.2.2
  - xz=5.2.10
  - yaml=0.2.5
  - zeromq=4.3.4
  - zipp=3.15.0
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
    - en-core-web-sm==3.5.0
